# Generated by Django 5.1.2 on 2024-11-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_listing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
