# Generated by Django 5.1.2 on 2024-11-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_alter_listing_description_alter_listing_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(
                blank=True,
                error_messages={"invalid": "Please enter a valid URL (https//)."},
            ),
        ),
    ]
