# Generated by Django 5.1.2 on 2024-11-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
