# Generated by Django 5.1.3 on 2025-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_comment_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
